import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/src/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js logo"
            width={180}
            height={38}
            priority
          />
          <ol>
            <li>
              <code>HotelManagement Website</code>.
            </li>
            <li>By: Vinh, Phúc, Nguyênư</li>
          </ol>

          <div className={styles.ctas}>
            <a
              className={styles.primary}
              href="/admin"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                className={styles.logo}
                src="/vercel.svg"
                alt="Vercel logomark"
                width={20}
                height={20}
              />
              Admin
            </a>
            <a
              href="/admin/test"
              target="_blank"
              rel="noopener noreferrer"
              className={styles.secondary}
            >
              Test Admin menu
            </a>
          </div>
        </main>
        <footer className={styles.footer}></footer>
      </div>
    </>
  );
}
